# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(help_text="Ex: 'Journée Portes Ouvertes ESGIS 2026'", max_length=255, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description détaillée')),
                ('description_courte', models.CharField(blank=True, help_text='Résumé pour les listes et partages', max_length=300, verbose_name='description courte')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='evenements/%Y/%m/', verbose_name='image principale')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='evenements/couvertures/%Y/%m/', verbose_name='image de couverture')),
                ('galerie_images', models.JSONField(blank=True, default=list, verbose_name="galerie d'images (URLs)")),
                ('type', models.CharField(choices=[('JPO', 'Journée portes ouvertes'), ('SALON', 'Salon / Forum des formations'), ('CONFERENCE', 'Conférence / Table ronde'), ('WEBINAIRE', 'Webinaire / Live en ligne'), ('ATELIER', 'Atelier pratique'), ('SEANCE_INFO', "Séance d'information"), ('CONCOURS', "Concours d'entrée"), ('PRESELECTION', 'Épreuve de présélection'), ('ORIENTATION', "Session d'orientation"), ('RENCONTRE', 'Rencontre avec des professionnels'), ('VISITE', "Visite d'entreprise / campus"), ('AUTRE', 'Autre')], default='JPO', max_length=20, verbose_name="type d'événement")),
                ('format', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('EN_LIGNE', '100% en ligne'), ('HYBRIDE', 'Hybride (présentiel + en ligne)')], default='PRESENTIEL', max_length=20, verbose_name='format')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ANNULE', 'Annulé'), ('REPORTÉ', 'Reporté'), ('TERMINE', 'Terminé (passé)')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('cible', models.CharField(choices=[('TOUS', 'Tous les étudiants'), ('TERMINALES', 'Élèves de Terminale'), ('LICENCE', 'Étudiants en Licence'), ('MASTER', 'Étudiants en Master'), ('PARENTS', 'Parents / Tuteurs'), ('CONSEILLERS', "Conseillers d'orientation"), ('PROFESSIONNELS', 'Professionnels')], default='TOUS', max_length=20, verbose_name='public cible')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute — À ne pas manquer'), ('CRITIQUE', 'Critique — Incontournable')], default='NORMALE', max_length=20, verbose_name='priorité')),
                ('date_debut', models.DateTimeField(db_index=True, verbose_name='date et heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='date et heure de fin')),
                ('date_limite_inscription', models.DateTimeField(blank=True, help_text="Laisser vide pour inscription libre jusqu'au début", null=True, verbose_name="date limite d'inscription")),
                ('lieu_nom', models.CharField(blank=True, help_text="Ex: 'Campus principal ESGIS'", max_length=255, verbose_name='nom du lieu')),
                ('adresse', models.CharField(blank=True, max_length=500, verbose_name='adresse complète')),
                ('ville', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ville')),
                ('pays', models.CharField(default='Togo', max_length=100, verbose_name='pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('lien_visio', models.URLField(blank=True, help_text='Lien Zoom, Google Meet, Teams, etc.', verbose_name='lien visioconférence')),
                ('plateforme_visio', models.CharField(blank=True, help_text="Ex: 'Zoom', 'Google Meet'", max_length=50, verbose_name='plateforme de visio')),
                ('code_acces', models.CharField(blank=True, max_length=100, verbose_name="code d'accès / mot de passe")),
                ('capacite_max', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='capacité maximale')),
                ('nombre_inscrits', models.PositiveIntegerField(default=0, verbose_name="nombre d'inscrits")),
                ('nombre_presents', models.PositiveIntegerField(default=0, verbose_name="nombre de présents (après l'événement)")),
                ('inscriptions_ouvertes', models.BooleanField(default=True, verbose_name='inscriptions ouvertes')),
                ('inscription_obligatoire', models.BooleanField(default=True, help_text="Si False, l'événement est accessible sans inscription", verbose_name='inscription obligatoire')),
                ('est_gratuit', models.BooleanField(default=True, verbose_name='événement gratuit')),
                ('cout_participation', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='coût de participation (FCFA)')),
                ('informations_tarifs', models.TextField(blank=True, verbose_name='informations sur les tarifs')),
                ('organisateur_externe', models.CharField(blank=True, help_text="Si l'organisateur n'est pas un établissement référencé", max_length=255, verbose_name='organisateur externe')),
                ('programme', models.JSONField(blank=True, default=list, help_text="Liste d'activités : [{'heure': '09:00', 'titre': 'Accueil', 'description': '...'}]", verbose_name="programme / agenda de l'événement")),
                ('intervenants', models.JSONField(blank=True, default=list, help_text="Liste : [{'nom': 'Dr. Mensah', 'fonction': 'Directeur', 'bio': '...'}]", verbose_name='intervenants')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Ex: ['informatique', 'bac+3', 'lomé']", verbose_name='tags / mots-clés')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=30, verbose_name='téléphone de contact')),
                ('site_web', models.URLField(blank=True, verbose_name="site web de l'événement")),
                ('reseaux_sociaux', models.JSONField(blank=True, default=dict, help_text="Ex: {'facebook': 'https://...', 'instagram': '...'}", verbose_name='liens réseaux sociaux')),
                ('envoi_rappel_j7', models.BooleanField(default=True, verbose_name='rappel automatique J-7')),
                ('envoi_rappel_j1', models.BooleanField(default=True, verbose_name='rappel automatique J-1')),
                ('envoi_rappel_j0', models.BooleanField(default=False, verbose_name='rappel automatique le jour J')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='nombre de vues de la fiche')),
                ('nombre_partages', models.PositiveIntegerField(default=0, verbose_name='nombre de partages')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL, verbose_name="créateur de l'événement")),
                ('domaines_concernes', models.ManyToManyField(blank=True, related_name='evenements', to='catalog.domaine', verbose_name='domaines concernés')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='catalog.etablissement', verbose_name='établissement organisateur')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('CONFIRME', 'Confirmé (email vérifié)'), ('LISTE_ATTENTE', "Liste d'attente"), ('ANNULE', 'Inscription annulée'), ('PRESENT', 'Présent (a participé)'), ('ABSENT', 'Inscrit mais absent')], default='INSCRIT', max_length=20, verbose_name='statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='date de confirmation')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="date d'annulation")),
                ('token_confirmation', models.CharField(blank=True, max_length=255, null=True, verbose_name='token de confirmation')),
                ('nombre_accompagnants', models.PositiveIntegerField(default=0, help_text="Ex: parent qui vient avec l'étudiant", verbose_name="nombre d'accompagnants")),
                ('besoins_speciaux', models.TextField(blank=True, help_text="Ex: 'Besoin d'un interprète LSF', 'Accès PMR'", verbose_name='besoins spéciaux / accessibilité')),
                ('source_inscription', models.CharField(blank=True, help_text="Ex: 'site_web', 'mobile_app', 'qr_code', 'recommandation'", max_length=50, verbose_name="source de l'inscription")),
                ('a_participe', models.BooleanField(default=False, verbose_name='a effectivement participé')),
                ('date_checkin', models.DateTimeField(blank=True, null=True, verbose_name='date de check-in')),
                ('feedback', models.TextField(blank=True, verbose_name="retour d'expérience")),
                ('note_satisfaction', models.PositiveIntegerField(blank=True, null=True, verbose_name='note de satisfaction (1-5)')),
                ('qr_code_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='token QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.evenement', verbose_name='événement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'inscription à un événement',
                'verbose_name_plural': 'inscriptions aux événements',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_debut', 'statut'], name='events_even_date_de_9cc2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['type', 'statut'], name='events_even_type_674e16_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['ville'], name='events_even_ville_7fb9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['-published_at'], name='events_even_publish_4925e1_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['etablissement'], name='events_even_etablis_69fa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionevenement',
            index=models.Index(fields=['utilisateur', 'statut'], name='events_insc_utilisa_8bd3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionevenement',
            index=models.Index(fields=['evenement', 'statut'], name='events_insc_eveneme_99df67_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionevenement',
            index=models.Index(fields=['-date_inscription'], name='events_insc_date_in_f65268_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscriptionevenement',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'evenement'), name='unique_inscription_evenement'),
        ),
    ]
