# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('events', '0001_initial'),
        ('orientation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('lien_utile', models.URLField(blank=True, verbose_name='lien utile')),
                ('documents_requis', models.JSONField(blank=True, default=list, verbose_name='documents requis')),
                ('is_active', models.BooleanField(default=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='catalog.etablissement', verbose_name='établissement associé')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='catalog.formation', verbose_name='formation associée')),
            ],
            options={
                'verbose_name': 'élément de checklist',
                'verbose_name_plural': 'éléments de checklist',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Voeu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorite', models.PositiveIntegerField(default=1, help_text='1 = choix n°1, 2 = choix n°2, etc.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='ordre de priorité')),
                ('niveau_priorite', models.CharField(choices=[('VITAL', 'Vital — Mon choix n°1'), ('IMPORTANT', 'Important — Très souhaité'), ('SOUHAITE', 'Souhaité — Intéressant'), ('SECURITE', 'Sécurité — Plan B'), ('EXPLORATOIRE', 'Exploratoire — À voir')], default='SOUHAITE', max_length=20, verbose_name='niveau de priorité')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', "Soumis à l'établissement"), ('EN_ATTENTE', 'En attente de réponse'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('LISTE_ATTENTE', "Liste d'attente"), ('ABANDONNE', "Abandonné par l'étudiant"), ('INSCRIT', 'Inscrit définitivement')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='date de soumission')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='date de réponse')),
                ('numero_candidature', models.CharField(blank=True, max_length=100, verbose_name='numéro de candidature')),
                ('lettre_motivation', models.TextField(blank=True, verbose_name='lettre de motivation')),
                ('commentaire_etablissement', models.TextField(blank=True, verbose_name="commentaire de l'établissement")),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('est_principal', models.BooleanField(default=False, help_text='Le voeu choisi en dernier lieu pour inscription finale', verbose_name='voeu principal (définitif)')),
                ('notes_etudiant', models.TextField(blank=True, verbose_name='notes personnelles')),
                ('derniere_action', models.DateTimeField(blank=True, null=True, verbose_name='dernière action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='voeux', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux', to='catalog.formation', verbose_name='formation visée')),
            ],
            options={
                'verbose_name': 'voeu',
                'verbose_name_plural': 'voeux',
                'ordering': ['priorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvenementAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('JPO', 'Journée portes ouvertes'), ('CONCOURS', 'Concours'), ('DATE_LIMITE', 'Date limite'), ('ENTRETIEN', 'Entretien / Oral'), ('RESULTAT', 'Publication résultats'), ('INSCRIPTION', 'Inscription administrative'), ('SALON', 'Salon / Forum'), ('WEBINAIRE', 'Webinaire'), ('PERSONNEL', 'Personnel')], default='PERSONNEL', max_length=20, verbose_name="type d'événement")),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('date_debut', models.DateTimeField(verbose_name='date et heure de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='date et heure de fin')),
                ('toute_la_journee', models.BooleanField(default=False, verbose_name='toute la journée')),
                ('rappel_j_30', models.BooleanField(default=False, verbose_name='rappel 30 jours avant')),
                ('rappel_j_7', models.BooleanField(default=True, verbose_name='rappel 7 jours avant')),
                ('rappel_j_1', models.BooleanField(default=True, verbose_name='rappel la veille')),
                ('rappel_j_0', models.BooleanField(default=False, verbose_name='rappel le jour même')),
                ('est_termine', models.BooleanField(default=False, verbose_name='terminé')),
                ('est_annule', models.BooleanField(default=False, verbose_name='annulé')),
                ('couleur', models.CharField(default='#3B82F6', max_length=7, verbose_name='couleur (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evenement_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_agenda', to='events.evenement', verbose_name='événement public associé')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_agenda', to='catalog.formation', verbose_name='formation associée')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_agenda', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('voeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_agenda', to='dashboard.voeu', verbose_name='voeu associé')),
            ],
            options={
                'verbose_name': "événement d'agenda",
                'verbose_name_plural': "événements d'agenda",
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemarcheInscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INSCRIPTION', 'Inscription administrative'), ('CONCOURS', "Concours d'entrée"), ('PRESELECTION', 'Présélection sur dossier'), ('BOURSE', 'Demande de bourse'), ('LOGEMENT', 'Demande de logement'), ('VISA', 'Demande de visa étudiant'), ('EQUIVALENCE', "Demande d'équivalence"), ('AUTRE', 'Autre démarche')], default='INSCRIPTION', max_length=20, verbose_name='type de démarche')),
                ('titre', models.CharField(help_text="Ex: 'Constituer le dossier d\\'inscription UL'", max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description / instructions')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('ENVOYEE', 'Envoyée / Déposée'), ('COMPLETEE', 'Complétée'), ('ANNULEE', 'Annulée'), ('ECHEANCE_PASSEE', 'Échéance passée')], default='A_FAIRE', max_length=20, verbose_name='statut')),
                ('progression', models.PositiveIntegerField(default=0, verbose_name='progression (%)')),
                ('date_echeance', models.DateTimeField(blank=True, help_text='Date limite pour compléter cette démarche', null=True, verbose_name="date d'échéance")),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='date de réalisation')),
                ('documents_requis', models.JSONField(blank=True, default=list, help_text="Ex: ['Relevé de notes', 'Copie BAC', 'Photo d\\'identité']", verbose_name='documents requis')),
                ('documents_fournis', models.JSONField(blank=True, default=list, verbose_name='documents fournis')),
                ('cout_estime', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='coût estimé (FCFA)')),
                ('rappel_actif', models.BooleanField(default=True, verbose_name='rappel actif')),
                ('jours_avant_rappel', models.PositiveIntegerField(default=7, help_text="Rappel envoyé X jours avant l'échéance", verbose_name='jours avant échéance pour rappel')),
                ('notes_etudiant', models.TextField(blank=True, verbose_name='notes personnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demarches', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demarches', to='catalog.formation', verbose_name='formation concernée')),
                ('voeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demarches', to='dashboard.voeu', verbose_name='voeu associé')),
            ],
            options={
                'verbose_name': "démarche d'inscription",
                'verbose_name_plural': "démarches d'inscription",
                'ordering': ['date_echeance', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('est_fait', models.BooleanField(default=False, verbose_name='fait')),
                ('date_fait', models.DateTimeField(blank=True, null=True, verbose_name='date de complétion')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_utilisateur', to='dashboard.checklistitem', verbose_name='élément')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('voeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='dashboard.voeu', verbose_name='voeu associé')),
            ],
            options={
                'verbose_name': 'checklist utilisateur',
                'verbose_name_plural': 'checklists utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_entite', models.CharField(choices=[('FORMATION', 'Formation'), ('METIER', 'Métier'), ('ETABLISSEMENT', 'Établissement'), ('EVENEMENT', 'Événement')], max_length=20, verbose_name="type d'entité")),
                ('note_personnelle', models.TextField(blank=True, help_text="Notes personnelles de l'utilisateur sur ce favori", verbose_name='note personnelle')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Ex: ['mon_top', 'a_visiter', 'comparer']", verbose_name='tags personnels')),
                ('source', models.CharField(blank=True, help_text="D'où vient le favori : recommandation, recherche, etc.", max_length=50, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='catalog.etablissement', verbose_name='établissement')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='events.evenement', verbose_name='événement')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='catalog.formation', verbose_name='formation')),
                ('metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='catalog.metier', verbose_name='métier')),
                ('recommandation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoris_crees', to='orientation.recommandation', verbose_name="recommandation d'origine")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'type_entite'], name='dashboard_f_utilisa_19beb5_idx'), models.Index(fields=['-created_at'], name='dashboard_f_created_051cf9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type_entite', 'FORMATION')), fields=('utilisateur', 'type_entite', 'formation'), name='unique_favori_formation'), models.UniqueConstraint(condition=models.Q(('type_entite', 'METIER')), fields=('utilisateur', 'type_entite', 'metier'), name='unique_favori_metier'), models.UniqueConstraint(condition=models.Q(('type_entite', 'ETABLISSEMENT')), fields=('utilisateur', 'type_entite', 'etablissement'), name='unique_favori_etablissement')],
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('date_envoi_prevue', models.DateTimeField(db_index=True, verbose_name="date d'envoi prévue")),
                ('date_envoi_effective', models.DateTimeField(blank=True, null=True, verbose_name="date d'envoi effective")),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push mobile'), ('SMS', 'SMS'), ('IN_APP', 'In-app')], default='IN_APP', max_length=20, verbose_name='canal de notification')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ENVOYE', 'Envoyé'), ('IGNORE', 'Ignoré'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demarche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='dashboard.demarcheinscription', verbose_name='démarche associée')),
                ('evenement_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='dashboard.evenementagenda', verbose_name='événement associé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'rappel',
                'verbose_name_plural': 'rappels',
                'ordering': ['date_envoi_prevue'],
                'indexes': [models.Index(fields=['statut', 'date_envoi_prevue'], name='dashboard_r_statut_8b2f45_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voeu',
            index=models.Index(fields=['etudiant', 'statut'], name='dashboard_v_etudian_b46ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='voeu',
            index=models.Index(fields=['etudiant', 'priorite'], name='dashboard_v_etudian_87fa53_idx'),
        ),
        migrations.AddConstraint(
            model_name='voeu',
            constraint=models.UniqueConstraint(fields=('etudiant', 'formation'), name='unique_voeu_par_formation'),
        ),
        migrations.AddIndex(
            model_name='evenementagenda',
            index=models.Index(fields=['utilisateur', 'date_debut'], name='dashboard_e_utilisa_9f740e_idx'),
        ),
        migrations.AddIndex(
            model_name='evenementagenda',
            index=models.Index(fields=['date_debut', 'date_fin'], name='dashboard_e_date_de_849a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='demarcheinscription',
            index=models.Index(fields=['etudiant', 'statut'], name='dashboard_d_etudian_43f843_idx'),
        ),
        migrations.AddIndex(
            model_name='demarcheinscription',
            index=models.Index(fields=['date_echeance'], name='dashboard_d_date_ec_fed8fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistutilisateur',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'item', 'voeu'), name='unique_checklist_instance'),
        ),
    ]
