# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Un utilisateur avec cet e-mail existe déjà.'}, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, help_text='Format international : +228 90 00 00 00', max_length=20, verbose_name='téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='photo de profil')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre/Non spécifié')], default='A', max_length=1, verbose_name='genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('PARENT', 'Parent/Tuteur'), ('COUNSELOR', "Conseiller d'orientation"), ('SCHOOL_REP', "Représentant d'établissement"), ('ADMIN', 'Administrateur')], db_index=True, default='STUDENT', max_length=20, verbose_name='rôle')),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu'), ('EN_ATTENTE', 'En attente de vérification')], default='ACTIF', max_length=20, verbose_name='statut du compte')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='e-mail vérifié')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='téléphone vérifié')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_token_expires', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='dernière IP de connexion')),
                ('timezone', models.CharField(default='Africa/Lome', max_length=50, verbose_name='fuseau horaire')),
                ('langue_preferee', models.CharField(default='fr', max_length=10, verbose_name='langue préférée')),
                ('profile_complete', models.BooleanField(default=False, verbose_name='profil complété')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière activité')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialites', models.JSONField(blank=True, default=list, help_text='Domaines de spécialisation', verbose_name='spécialités')),
                ('qualifications', models.TextField(blank=True, verbose_name='qualifications/diplômes')),
                ('annees_experience', models.PositiveIntegerField(default=0, verbose_name="années d'expérience")),
                ('numero_agrement', models.CharField(blank=True, max_length=100, verbose_name="numéro d'agrément")),
                ('nombre_eleves_suivis', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible pour mentorat')),
                ('tarif_consultation', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='tarif consultation (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissements_suivis', models.ManyToManyField(blank=True, related_name='conseillers', to='catalog.etablissement', verbose_name='établissements suivis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil conseiller',
                'verbose_name_plural': 'profils conseillers',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profession')),
                ('preferences_orientation', models.JSONField(blank=True, default=list, help_text="Souhaits des parents pour l'orientation", verbose_name="préférences d'orientation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfants_suivis', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='parents_tuteurs', to=settings.AUTH_USER_MODEL, verbose_name='enfants suivis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil parent',
                'verbose_name_plural': 'profils parents',
            },
        ),
        migrations.CreateModel(
            name='SchoolRepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100, verbose_name='poste/fonction')),
                ('telephone_pro', models.CharField(blank=True, max_length=20, verbose_name='téléphone professionnel')),
                ('date_nomination', models.DateField(blank=True, null=True, verbose_name='date de nomination')),
                ('can_publish_events', models.BooleanField(default=True, verbose_name='peut publier des événements')),
                ('can_edit_formation', models.BooleanField(default=True, verbose_name='peut modifier les formations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representant', to='catalog.etablissement', verbose_name='établissement représenté')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_rep_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil représentant établissement',
                'verbose_name_plural': 'profils représentants établissement',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_bac', models.CharField(blank=True, choices=[('A', 'Série A (Lettres)'), ('C', 'Série C (Maths)'), ('D', 'Série D (SVT)'), ('E', 'Série E (Technique)'), ('G2', 'Série G2 (Éco-Gestion)'), ('TI', 'Série TI (Technique Industriel)'), ('TGC', 'Série TGC (Technique Comptable)'), ('AUTRE', 'Autre')], max_length=10, verbose_name='série de bac')),
                ('annee_bac', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)], verbose_name='année du bac')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='moyenne générale')),
                ('mentions_obtenues', models.JSONField(blank=True, default=list, help_text="Ex: ['Passable', 'Assez Bien']", verbose_name='mentions obtenues')),
                ('etablissement_scolaire', models.CharField(blank=True, max_length=255, verbose_name='lycée/établissement actuel')),
                ('ville_etablissement', models.CharField(blank=True, max_length=100, verbose_name="ville de l'établissement")),
                ('centres_interet', models.JSONField(blank=True, default=list, help_text="Liste des domaines d'intérêt", verbose_name="centres d'intérêt")),
                ('matieres_fortes', models.JSONField(blank=True, default=list, verbose_name='matières fortes')),
                ('matieres_faibles', models.JSONField(blank=True, default=list, verbose_name='matières faibles')),
                ('contraintes_financieres', models.BooleanField(default=False, verbose_name='contraintes financières')),
                ('budget_max_annuel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='budget max annuel (FCFA)')),
                ('mobilite_geographique', models.BooleanField(default=True, verbose_name='mobilité géographique')),
                ('villes_preferees', models.JSONField(blank=True, default=list, verbose_name='villes préférées')),
                ('projet_professionnel', models.TextField(blank=True, verbose_name='projet professionnel')),
                ('metiers_envisages', models.JSONField(blank=True, default=list, verbose_name='métiers envisagés')),
                ('nombre_tests_passes', models.PositiveIntegerField(default=0)),
                ('dernier_test_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil étudiant',
                'verbose_name_plural': 'profils étudiants',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='accounts_us_created_d650d4_idx'),
        ),
    ]
