# Generated by Django 6.0.6 on 2026-06-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='PDF, JPG ou PNG — 5 Mo max.', upload_to='verifications/%Y/%m/', verbose_name='document justificatif')),
                ('type_document', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('DIPLOME', 'Diplôme ou attestation'), ('LETTRE_MISSION', "Lettre de mission / d'employeur"), ('AUTRE', 'Autre document officiel')], default='CNI', max_length=20, verbose_name='type de document')),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis — en attente de traitement'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], db_index=True, default='SOUMIS', max_length=20, verbose_name='statut')),
                ('note_admin', models.TextField(blank=True, help_text="Visible par l'utilisateur en cas de rejet.", verbose_name='note / motif de rejet')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='soumis le')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_traitees', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_document', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'document de vérification',
                'verbose_name_plural': 'documents de vérification',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
