# Generated by Django 5.1.3 on 2026-07-02 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notesetudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='nombre_accompagnements_actifs',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre d'accompagnements actifs"),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='nombre_accompagnements_total',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre total d'accompagnements"),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='nombre_evaluations',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre d'évaluations reçues"),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='note_moyenne',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne (0-5)'),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='solde_ristournes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='solde ristournes (FCFA)'),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='taux_ristourne',
            field=models.FloatField(default=10.0, help_text='Pourcentage du tarif consultation reversé comme commission', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='taux de ristourne (%)'),
        ),
    ]
