# Generated by Django 5.1.3 on 2026-07-10 11:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='annee_bac',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2040)], verbose_name='année du bac'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(help_text="Secret base32 partagé entre le serveur et l'app d'authentification", max_length=64, verbose_name='secret TOTP')),
                ('name', models.CharField(default='AvenSU-Orienta', help_text="Nom affiché dans l'application d'authentification (Google Authenticator, etc.)", max_length=128, verbose_name='nom du dispositif')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='activé')),
                ('is_verified', models.BooleanField(default=False, help_text="Indique si l'utilisateur a confirmé possession du secret en saisissant un code valide", verbose_name='vérifié')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text="Liste de codes hashés permettant de récupérer l'accès en cas de perte du téléphone", verbose_name='codes de secours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière utilisation')),
                ('last_challenge_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier défi envoyé')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'dispositif TOTP',
                'verbose_name_plural': 'dispositifs TOTP',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='token de défi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('is_consumed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP à l'origine du défi (audit)", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_challenges', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'défi 2FA',
                'verbose_name_plural': 'défis 2FA',
                'ordering': ['-created_at'],
            },
        ),
    ]
