# Generated by Django 5.1.3 on 2026-07-12 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_two_factor_totp'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentementParental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_parent', models.EmailField(help_text="Email saisi par l'étudiant mineur lors de l'inscription", max_length=254, verbose_name='email du parent')),
                ('nom_parent', models.CharField(blank=True, help_text="Nom saisi par l'étudiant (prénom + nom)", max_length=255, verbose_name='nom du parent')),
                ('relation', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR_LEGAL', 'Tuteur légal'), ('AUTRE', 'Autre')], default='PERE', max_length=20, verbose_name="relation avec l'étudiant")),
                ('token', models.CharField(max_length=128, unique=True, verbose_name='token de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(help_text='Délai de 14 jours pour valider', verbose_name="date d'expiration")),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente — email envoyé au parent'), ('VALIDE', 'Validé par le parent'), ('REFUSE', 'Refusé par le parent'), ('EXPIRE', 'Expiré (délai de 14 jours dépassé)')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('ip_validation', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_validation', models.CharField(blank=True, max_length=512)),
                ('consentement_rgpd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentements_parentaux', to='compliance.consentementrgpd', verbose_name='consentement RGPD signé')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_consentement_parental', to=settings.AUTH_USER_MODEL, verbose_name='étudiant mineur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentements_enfants', to=settings.AUTH_USER_MODEL, verbose_name='parent/tuteur')),
            ],
            options={
                'verbose_name': 'consentement parental',
                'verbose_name_plural': 'consentements parentaux',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['etudiant', 'statut'], name='accounts_co_etudian_f2a9ea_idx'), models.Index(fields=['email_parent', 'statut'], name='accounts_co_email_p_07281b_idx')],
            },
        ),
    ]
