# Generated by Django 5.1.3 on 2026-07-12 05:35

import apps.compliance.encryption_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parental_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentementparental',
            name='nom_parent',
            field=apps.compliance.encryption_fields.EncryptedCharField(blank=True, help_text="Nom saisi par l'étudiant (prénom + nom) — chiffré au repos", max_length=255, verbose_name='nom du parent'),
        ),
    ]
