# Generated by Django 5.1.3 on 2026-07-10 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('COLLEGE', 'Collège — Découverte de soi'), ('LYCEE', 'Lycée — Choix stratégiques'), ('POST_BAC', 'Post-Bac — Admission & carrière')], db_index=True, max_length=15, verbose_name='phase')),
                ('categorie', models.CharField(choices=[('DECOUVERTE', 'Découverte de soi / secteurs'), ('ORIENTATION', "Tests d'orientation"), ('ACADEMIQUE', 'Choix académiques / spécialités'), ('CONCOURS', 'Préparation aux concours / examens'), ('CANDIDATURE', 'Candidatures aux écoles'), ('ADMISSION', 'Admission & inscription administrative'), ('STAGE', 'Recherche de stage / alternance'), ('INSERTION', 'Insertion professionnelle'), ('FINANCEMENT', 'Financement (bourses, prêts)')], db_index=True, max_length=20, verbose_name='catégorie')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la phase", verbose_name='ordre')),
                ('ressource_externe_url', models.URLField(blank=True, help_text='Lien vers une page de la plateforme ou externe', verbose_name='URL ressource externe')),
                ('critere_completion', models.TextField(blank=True, help_text="Description de ce qui valide l'étape (ex: 'Test RIASEC passé')", verbose_name='critère de complétion')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='âge minimum recommandé')),
                ('age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='âge maximum recommandé')),
                ('is_active', models.BooleanField(default=True)),
                ('is_obligatoire', models.BooleanField(default=False, help_text='Étape obligatoire pour valider la phase', verbose_name='obligatoire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'étape de roadmap',
                'verbose_name_plural': 'étapes de roadmap',
                'ordering': ['phase', 'ordre', 'titre'],
                'indexes': [models.Index(fields=['phase', 'is_active'], name='roadmap_eta_phase_7e3182_idx'), models.Index(fields=['categorie'], name='roadmap_eta_categor_46b2f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='JalonRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('COLLEGE', 'Collège — Découverte de soi'), ('LYCEE', 'Lycée — Choix stratégiques'), ('POST_BAC', 'Post-Bac — Admission & carrière')], max_length=15, verbose_name='phase')),
                ('date_evenement', models.DateField(db_index=True, verbose_name="date de l'événement")),
                ('is_national', models.BooleanField(default=True, verbose_name='national')),
                ('pays', models.CharField(default='Togo', max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('url_inscription', models.URLField(blank=True)),
                ('is_annuel', models.BooleanField(default=False, verbose_name='annuel')),
                ('concerne_tous', models.BooleanField(default=True, verbose_name='concerne tous les étudiants de la phase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiants_cibles', models.ManyToManyField(blank=True, related_name='jalons_roadmap', to=settings.AUTH_USER_MODEL, verbose_name='étudiants ciblés')),
            ],
            options={
                'verbose_name': 'jalon de roadmap',
                'verbose_name_plural': 'jalons de roadmap',
                'ordering': ['date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='EtapePersonnelleEtudiant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('COLLEGE', 'Collège — Découverte de soi'), ('LYCEE', 'Lycée — Choix stratégiques'), ('POST_BAC', 'Post-Bac — Admission & carrière')], max_length=15, verbose_name='phase')),
                ('categorie', models.CharField(choices=[('DECOUVERTE', 'Découverte de soi / secteurs'), ('ORIENTATION', "Tests d'orientation"), ('ACADEMIQUE', 'Choix académiques / spécialités'), ('CONCOURS', 'Préparation aux concours / examens'), ('CANDIDATURE', 'Candidatures aux écoles'), ('ADMISSION', 'Admission & inscription administrative'), ('STAGE', 'Recherche de stage / alternance'), ('INSERTION', 'Insertion professionnelle'), ('FINANCEMENT', 'Financement (bourses, prêts)')], default='DECOUVERTE', max_length=20, verbose_name='catégorie')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('NON_COMMENCE', 'Non commencé'), ('EN_COURS', 'En cours'), ('COMPLETE', 'Complété'), ('BLOQUE', 'Bloqué'), ('ANNULE', 'Annulé')], default='NON_COMMENCE', max_length=15, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_objectif', models.DateTimeField(blank=True, help_text="Date à laquelle l'étudiant vise de compléter l'étape", null=True, verbose_name='date objectif')),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('notes_personnelles', models.TextField(blank=True)),
                ('conseiller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_roadmap_supervisees', to=settings.AUTH_USER_MODEL, verbose_name='conseiller')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_roadmap', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('etape_generique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances_etudiants', to='roadmap.etaperoadmap', verbose_name='étape générique (template)')),
            ],
            options={
                'verbose_name': "étape personnelle d'étudiant",
                'verbose_name_plural': "étapes personnelles d'étudiants",
                'ordering': ['phase', 'ordre', 'date_objectif'],
                'indexes': [models.Index(fields=['etudiant', 'phase', 'statut'], name='roadmap_eta_etudian_67a636_idx'), models.Index(fields=['date_objectif'], name='roadmap_eta_date_ob_cc0317_idx')],
            },
        ),
    ]
