# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, help_text='Généré à partir du premier message utilisateur', max_length=255, verbose_name='titre auto-généré')),
                ('canal', models.CharField(choices=[('WEB', 'Site web'), ('MOBILE', 'Application mobile'), ('API', 'API externe')], default='WEB', max_length=20, verbose_name="canal d'origine")),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée'), ('SIGNELEE', 'Signalée (modération)')], default='ACTIVE', max_length=20, verbose_name='statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('contexte_utilisateur', models.JSONField(blank=True, default=dict, help_text='Snapshot du profil, derniers résultats de test, favoris. Injecté dans le prompt système.', verbose_name='contexte utilisateur')),
                ('nombre_messages', models.PositiveIntegerField(default=0)),
                ('nombre_messages_utilisateur', models.PositiveIntegerField(default=0)),
                ('nombre_messages_assistant', models.PositiveIntegerField(default=0)),
                ('tokens_utilises', models.PositiveIntegerField(default=0, verbose_name='tokens consommés')),
                ('cout_estime_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='coût estimé (USD)')),
                ('duree_totale_secondes', models.PositiveIntegerField(default=0, verbose_name='durée totale de la conversation (secondes)')),
                ('note_satisfaction', models.PositiveIntegerField(blank=True, null=True, verbose_name='note de satisfaction (1-5)')),
                ('feedback_utilisateur', models.TextField(blank=True, verbose_name='feedback utilisateur')),
                ('signale', models.BooleanField(default=False, verbose_name='conversation signalée')),
                ('motif_signalement', models.TextField(blank=True, verbose_name='motif de signalement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dernier_message_at', models.DateTimeField(blank=True, null=True, verbose_name='date du dernier message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_chatbot', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SYSTEM', 'Système'), ('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant'), ('TOOL', 'Outil / Handler')], max_length=20, verbose_name='rôle')),
                ('contenu', models.TextField(help_text='Texte du message (Markdown supporté)', verbose_name='contenu du message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles : intent, entities, sources, latence, tokens, etc.', verbose_name='métadonnées')),
                ('intent_detecte', models.CharField(blank=True, help_text="Code de l'intention détectée pour ce message", max_length=50, verbose_name='intention détectée')),
                ('confiance_intent', models.FloatField(default=0, verbose_name="confiance de l'intent (0-1)")),
                ('source_reponse', models.CharField(blank=True, choices=[('HANDLER_METIER', 'Handler métier (données structurées)'), ('RAG', 'Base de connaissances (RAG)'), ('LLM_DIRECT', 'LLM général (sans contexte)'), ('CATALOGUE', 'Catalogue (formations/métiers)'), ('ORIENTATION', "Résultats d'orientation"), ('FALLBACK', 'Réponse par défaut')], max_length=30, verbose_name='source de la réponse')),
                ('handler_utilise', models.CharField(blank=True, max_length=100, verbose_name='handler utilisé')),
                ('tokens_prompt', models.PositiveIntegerField(default=0, verbose_name='tokens du prompt')),
                ('tokens_completion', models.PositiveIntegerField(default=0, verbose_name='tokens de la complétion')),
                ('tokens_total', models.PositiveIntegerField(default=0, verbose_name='tokens totaux')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='tokens utilisés (alias)')),
                ('modele_utilise', models.CharField(blank=True, max_length=50, verbose_name='modèle utilisé')),
                ('latence_ms', models.PositiveIntegerField(default=0, verbose_name='latence (ms)')),
                ('sources_citees', models.JSONField(blank=True, default=list, help_text="Liste des sources utilisées pour la réponse : [{'type': 'formation', 'id': '...', 'titre': '...'}]", verbose_name='sources citées')),
                ('feedbackpositif', models.BooleanField(blank=True, null=True, verbose_name='réponse utile')),
                ('entites_extraites', models.JSONField(blank=True, default=dict, help_text="Ex: {'domaine': 'informatique', 'ville': 'Lomé', 'budget': 500000}", verbose_name='entités extraites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['utilisateur', '-updated_at'], name='chatbot_con_utilisa_e2ea4f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['statut'], name='chatbot_con_statut_1e3c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['intent_detecte'], name='chatbot_mes_intent__0968df_idx'),
        ),
    ]
