# Generated by Django 5.1.3 on 2026-07-10 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolitiqueConservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('IDENTITE', 'Identité (nom, email, téléphone)'), ('SCOLAIRE', 'Données scolaires (notes, bulletins)'), ('ORIENTATION', "Tests d'orientation et résultats"), ('MESSAGERIE', 'Messages et conversations'), ('COMMUNAUTE', 'Posts et contributions communautaires'), ('FINANCIERE', 'Données financières (paiements)'), ('ANALYTICS', "Données d'analytics et logs"), ('DOCUMENTS', 'Documents vérification (CNI, diplômes)')], max_length=20, unique=True, verbose_name='catégorie de donnée')),
                ('duree_conservation_jours', models.PositiveIntegerField(help_text="Durée à compter de la dernière activité de l'utilisateur", verbose_name='durée de conservation (jours)')),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'politique de conservation',
                'verbose_name_plural': 'politiques de conservation',
            },
        ),
        migrations.CreateModel(
            name='ConsentementRGPD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INSCRIPTION', 'Inscription à la plateforme'), ('TEST_ORIENTATION', "Passation d'un test d'orientation"), ('PARTAGE_CONSEILLER', 'Partage de données avec un conseiller'), ('PARTAGE_ETABLISSEMENT', 'Partage de données avec un établissement'), ('MARKETING', 'Recevoir des communications marketing'), ('PROFILAGE_IA', "Utilisation de l'IA pour recommandations personnalisées"), ('MESSAGERIE', 'Utilisation de la messagerie interne'), ('PARENTAL', 'Consentement parental pour mineur'), ('COOKIES', 'Acceptation des cookies non essentiels'), ('ANALYTICS', "Collecte de données d'analytics")], db_index=True, max_length=30, verbose_name='type de consentement')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Actif'), ('RETIRE', 'Retiré'), ('EXPIRE', 'Expiré')], default='ACTIVE', max_length=10, verbose_name='statut')),
                ('texte_consentement', models.TextField(help_text="Version exacte du texte accepté par l'utilisateur", verbose_name='texte du consentement')),
                ('version_politique', models.CharField(default='1.0', max_length=20, verbose_name='version de la politique de confidentialité')),
                ('date_consentement', models.DateTimeField(auto_now_add=True, verbose_name='date du consentement')),
                ('date_retrait', models.DateTimeField(blank=True, null=True, verbose_name='date de retrait')),
                ('ip_consentement', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP au moment du consentement')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentements_parentaux_donnes', to=settings.AUTH_USER_MODEL, verbose_name='parent/tuteur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'consentement RGPD',
                'verbose_name_plural': 'consentements RGPD',
                'ordering': ['-date_consentement'],
                'indexes': [models.Index(fields=['utilisateur', 'type', 'statut'], name='compliance__utilisa_d7283a_idx'), models.Index(fields=['date_consentement'], name='compliance__date_co_ae1e14_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandeRGPD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, help_text='Référence unique de la demande (ex: RGPD-2026-001234)', max_length=32, unique=True, verbose_name='référence')),
                ('type', models.CharField(choices=[('ACCES', "Droit d'accès (art. 15)"), ('RECTIFICATION', 'Droit de rectification (art. 16)'), ('EFFACEMENT', "Droit à l'oubli (art. 17)"), ('LIMITATION', 'Limitation du traitement (art. 18)'), ('PORTABILITE', 'Portabilité des données (art. 20)'), ('OPPOSITION', 'Opposition au traitement (art. 21)')], max_length=20, verbose_name='type de demande')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('REFUSEE', 'Refusée (motif légal)')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('motif', models.TextField(blank=True, help_text="Précisions apportées par l'utilisateur (notamment pour rectification/effacement)", verbose_name='motif / précisions')),
                ('motif_refus', models.TextField(blank=True, help_text='Rempli par le DPO si la demande est refusée pour motif légal', verbose_name='motif de refus')),
                ('donnees_exportees', models.JSONField(blank=True, default=dict, help_text='Snapshot JSON des données au moment du traitement', verbose_name='données exportées')),
                ('fichier_export_url', models.URLField(blank=True, help_text="Lien signé temporaire vers le fichier ZIP d'export", verbose_name="URL du fichier d'export")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('date_limite', models.DateTimeField(help_text="Délai légal d'1 mois à compter de la demande", verbose_name='date limite de réponse')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_rgpd_traitees', to=settings.AUTH_USER_MODEL, verbose_name='traitée par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_rgpd', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'demande RGPD',
                'verbose_name_plural': 'demandes RGPD',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'statut'], name='compliance__utilisa_a8d25f_idx'), models.Index(fields=['date_limite'], name='compliance__date_li_952f26_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalTraitement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(help_text='Ex: ACCES, MODIFICATION, EXPORT, SUPPRESSION', max_length=50, verbose_name='action')),
                ('categorie_donnee', models.CharField(choices=[('IDENTITE', 'Identité (nom, email, téléphone)'), ('SCOLAIRE', 'Données scolaires (notes, bulletins)'), ('ORIENTATION', "Tests d'orientation et résultats"), ('MESSAGERIE', 'Messages et conversations'), ('COMMUNAUTE', 'Posts et contributions communautaires'), ('FINANCIERE', 'Données financières (paiements)'), ('ANALYTICS', "Données d'analytics et logs"), ('DOCUMENTS', 'Documents vérification (CNI, diplômes)')], max_length=20, verbose_name='catégorie de donnée')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Détails supplémentaires (objet concerné, champs modifiés, etc.)', verbose_name='détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_traitement_rgpd', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_accedees_par', to=settings.AUTH_USER_MODEL, verbose_name='données appartenant à')),
            ],
            options={
                'verbose_name': 'entrée du journal de traitement',
                'verbose_name_plural': 'entrées du journal de traitement',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cible', 'timestamp'], name='compliance__cible_i_a8c0b4_idx'), models.Index(fields=['acteur', 'timestamp'], name='compliance__acteur__c8063b_idx')],
            },
        ),
    ]
