# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code unique')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_courte', models.CharField(blank=True, max_length=300, verbose_name='description courte')),
                ('type_abonnement', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('CONSEILLER', 'Conseiller'), ('ETABLISSEMENT', 'Établissement'), ('ENTREPRISE', 'Entreprise / Partenaire')], default='ETUDIANT', max_length=20, verbose_name='type')),
                ('niveau', models.CharField(choices=[('GRATUIT', 'Gratuit (Basic)'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Professionnel'), ('ENTREPRISE', 'Entreprise')], default='STANDARD', max_length=20, verbose_name='niveau')),
                ('frequence', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel'), ('UNIQUE', 'Paiement unique')], default='MENSUEL', max_length=20, verbose_name='fréquence')),
                ('prix_fcfa', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix (FCFA)')),
                ('prix_promo_fcfa', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='prix promotionnel (FCFA)')),
                ('devise', models.CharField(default='XOF', max_length=10, verbose_name='devise')),
                ('periode_essai_jours', models.PositiveIntegerField(default=0, verbose_name="période d'essai (jours)")),
                ('duree_mois', models.PositiveIntegerField(default=1, verbose_name='durée (mois)')),
                ('fonctionnalites', models.JSONField(blank=True, default=list, verbose_name='fonctionnalités incluses')),
                ('limites', models.JSONField(blank=True, default=dict, verbose_name="limites d'utilisation")),
                ('avantages', models.JSONField(blank=True, default=list, verbose_name='avantages mis en avant')),
                ('icone', models.CharField(default='⭐', max_length=10, verbose_name='icône')),
                ('couleur', models.CharField(default='#3B82F6', max_length=7, verbose_name='couleur (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ['type_abonnement', 'ordre', 'prix_fcfa'],
                'indexes': [models.Index(fields=['type_abonnement', 'niveau'], name='payments_pl_type_ab_592c2b_idx'), models.Index(fields=['is_active', 'is_public'], name='payments_pl_is_acti_f6b4d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ESSAI', "En période d'essai"), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('RETARD', 'Retard de paiement'), ('BLOQUE', 'Bloqué (impayé)')], default='ACTIF', max_length=20, verbose_name='statut')),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('date_essai_fin', models.DateTimeField(blank=True, null=True, verbose_name="fin d'essai")),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name='date annulation')),
                ('date_dernier_paiement', models.DateTimeField(blank=True, null=True, verbose_name='date dernier paiement')),
                ('renouvellement_auto', models.BooleanField(default=True, verbose_name='renouvellement automatique')),
                ('methode_paiement_defaut', models.CharField(blank=True, max_length=20, verbose_name='méthode paiement défaut')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('consommation_courante', models.JSONField(blank=True, default=dict, verbose_name='consommation courante')),
                ('date_reset_consommation', models.DateTimeField(blank=True, null=True, verbose_name='date reset consommation')),
                ('nombre_renouvellements', models.PositiveIntegerField(default=0)),
                ('motif_annulation', models.TextField(blank=True, verbose_name='motif annulation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='payments.planabonnement', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='référence unique')),
                ('type', models.CharField(choices=[('ABONNEMENT', 'Abonnement'), ('RENOUVELLEMENT', 'Renouvellement automatique'), ('ACHAT_UNITE', "Achat à l'unité"), ('UPGRADE', 'Upgrade de plan'), ('REMBOURSEMENT', 'Remboursement'), ('CREDIT', 'Crédit / Bonus')], max_length=20, verbose_name='type de transaction')),
                ('methode_paiement', models.CharField(choices=[('FLOOZ', 'Togocom Flooz'), ('TMONEY', 'T-Money'), ('MOOV_MONEY', 'Moov Money'), ('ORANGE_MONEY', 'Orange Money'), ('CARTE', 'Carte bancaire (Stripe)'), ('VIREMENT', 'Virement bancaire'), ('GRATUIT', 'Gratuit / Offre spéciale')], max_length=20, verbose_name='méthode de paiement')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('frais_transaction', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='frais transaction (FCFA)')),
                ('montant_net', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='montant net reçu (FCFA)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('INITIEE', 'Initiée'), ('CONFIRMEE', 'Confirmée / Réussie'), ('ECHEC', 'Échec'), ('ANNULEE', 'Annulée'), ('REMBOURSEE', 'Remboursée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('telephone_payeur', models.CharField(blank=True, max_length=20, verbose_name='téléphone du payeur')),
                ('reference_externe', models.CharField(blank=True, max_length=255, verbose_name='référence externe')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('date_initiation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nombre_tentatives', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.abonnement', verbose_name='abonnement lié')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.planabonnement', verbose_name='plan concerné')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date_initiation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='numéro de facture')),
                ('montant_ht', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='montant HT (FCFA)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='montant TVA (FCFA)')),
                ('montant_ttc', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='montant TTC (FCFA)')),
                ('remise', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='remise (FCFA)')),
                ('lignes', models.JSONField(blank=True, default=list, verbose_name='lignes de facture')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='date de paiement')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=20, verbose_name='statut')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/%Y/%m/', verbose_name='fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='payments.abonnement', verbose_name='abonnement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date_emission'],
                'indexes': [models.Index(fields=['utilisateur', '-date_emission'], name='payments_fa_utilisa_18c46a_idx'), models.Index(fields=['statut'], name='payments_fa_statut_559fb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('devise', models.CharField(default='XOF', max_length=10, verbose_name='devise')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complété'), ('FAILED', 'Échec'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='statut')),
                ('provider', models.CharField(choices=[('FLOOZ', 'Togocom Flooz'), ('TMONEY', 'T-Money'), ('MOOV_MONEY', 'Moov Money'), ('ORANGE_MONEY', 'Orange Money'), ('CARTE', 'Carte bancaire (Stripe)'), ('VIREMENT', 'Virement bancaire'), ('GRATUIT', 'Gratuit / Offre spéciale')], default='FLOOZ', max_length=20, verbose_name='provider')),
                ('reference', models.CharField(help_text='Référence interne unique (ex: PAY-20260627-AB12CD)', max_length=100, unique=True, verbose_name='référence')),
                ('transaction_id', models.CharField(blank=True, help_text="ID retourné par l'opérateur", max_length=255, verbose_name='ID de transaction')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles (IP, user agent, etc.)', verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_725f02_idx'), models.Index(fields=['statut'], name='payments_pa_statut_3be74b_idx'), models.Index(fields=['reference'], name='payments_pa_referen_2444ed_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='abonnement',
            index=models.Index(fields=['utilisateur', 'statut'], name='payments_ab_utilisa_7df9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='abonnement',
            index=models.Index(fields=['date_fin'], name='payments_ab_date_fi_d4d26c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['utilisateur', '-date_initiation'], name='payments_tr_utilisa_56524c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['statut'], name='payments_tr_statut_7ec9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='payments_tr_referen_530efe_idx'),
        ),
    ]
