# Generated by Django 5.1.3 on 2026-07-02 04:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0003_demandeaccompagnement_messageaccompagnement_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RistourneConseiller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant de la ristourne (FCFA)')),
                ('taux_applique', models.FloatField(default=10.0, verbose_name='taux appliqué (%)')),
                ('note_etudiant', models.FloatField(blank=True, null=True, verbose_name="note donnée par l'étudiant")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='référence')),
                ('notes_admin', models.TextField(blank=True, verbose_name='notes admin')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('conseiller', models.ForeignKey(limit_choices_to={'role': 'COUNSELOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ristournes', to=settings.AUTH_USER_MODEL, verbose_name='conseiller')),
                ('demande_accompagnement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ristourne', to='orientation.demandeaccompagnement', verbose_name="demande d'accompagnement")),
            ],
            options={
                'verbose_name': 'ristourne conseiller',
                'verbose_name_plural': 'ristournes conseillers',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['conseiller', 'statut'], name='payments_ri_conseil_7cec30_idx')],
            },
        ),
    ]
