# Generated by Django 5.1.3 on 2026-07-10 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ristourneconseiller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant'),
        ),
    ]
