# Generated by Django 5.1.3 on 2026-07-10 11:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_simulateur_admission_visites_3d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentCandidats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='nom du segment')),
                ('description', models.TextField(blank=True)),
                ('regions', models.JSONField(blank=True, default=list, help_text="Liste de régions/villes. Ex: ['Lomé', 'Kara', 'Sokodé']", verbose_name='régions ciblées')),
                ('pays', models.JSONField(blank=True, default=list, verbose_name='pays ciblés')),
                ('moyenne_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='moyenne minimale')),
                ('moyenne_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='moyenne maximale')),
                ('niveau_actuel', models.JSONField(blank=True, default=list, help_text="Ex: ['TERMINALE', 'POST_BAC']", verbose_name='niveaux scolaires ciblés')),
                ('series_bac', models.JSONField(blank=True, default=list, help_text="Ex: ['C', 'D', 'G2']", verbose_name='séries de bac ciblées')),
                ('code_riasec_cible', models.JSONField(blank=True, default=list, help_text="Ex: ['RIA', 'SAE'] — candidats dont le profil contient ces codes", verbose_name='codes RIASEC ciblés')),
                ('domaines_interet', models.JSONField(blank=True, default=list, help_text="Ex: ['Informatique', 'Santé']", verbose_name="domaines d'intérêt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'segment de candidats',
                'verbose_name_plural': 'segments de candidats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampagneMarketing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='nom de la campagne')),
                ('description', models.TextField(blank=True)),
                ('message_principal', models.TextField(help_text='Message affiché aux candidats ciblés', verbose_name='message principal')),
                ('appel_action', models.CharField(help_text="Ex: 'Postulez avant le 30 juin'", max_length=255, verbose_name="appel à l'action")),
                ('url_destination', models.URLField(blank=True, help_text='Page vers laquelle le candidat est redirigé', verbose_name='URL de destination')),
                ('visuel', models.ImageField(blank=True, null=True, upload_to='marketing/visuels/%Y/%m/', verbose_name='visuel')),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIVE', 'Active'), ('PAUSE', 'En pause'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=15, verbose_name='statut')),
                ('budget_fcfa', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='budget (FCFA)')),
                ('cout_par_lead_qualifie', models.DecimalField(decimal_places=0, default=500, help_text='Montant facturé pour chaque lead qualifié (contact initié)', max_digits=10, verbose_name='coût par lead qualifié (FCFA)')),
                ('vues', models.PositiveIntegerField(default=0)),
                ('clics', models.PositiveIntegerField(default=0)),
                ('leads_generes', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes_marketing', to='catalog.etablissement', verbose_name='établissement')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes', to='marketing.segmentcandidats', verbose_name='segment ciblé')),
            ],
            options={
                'verbose_name': 'campagne marketing',
                'verbose_name_plural': 'campagnes marketing',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LeadQualifie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_matching', models.FloatField(default=0, help_text='Pourcentage de correspondance avec le segment ciblé', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score de matching')),
                ('critères_matches', models.JSONField(default=dict, help_text="Détail des critères qui matchent : {'region': True, 'moyenne': 14.5, ...}", verbose_name='critères matchés')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('CONTACTE', 'Contacté'), ('INTERESSE', 'Intéressé'), ('QUALIFIE', 'Qualifié'), ('CONVERTI', 'Converti (candidature)'), ('REFUSE', 'Refusé'), ('INJOIGNABLE', 'Injoignable')], default='NOUVEAU', max_length=15, verbose_name='statut')),
                ('is_facture', models.BooleanField(default=False, help_text="True si l'établissement a initié un contact (facturation au lead)", verbose_name='facturé')),
                ('date_facturation', models.DateTimeField(blank=True, null=True)),
                ('montant_facture', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='montant facturé')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_premier_contact', models.DateTimeField(blank=True, null=True)),
                ('date_conversion', models.DateTimeField(blank=True, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='marketing.campagnemarketing')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_recus', to=settings.AUTH_USER_MODEL, verbose_name='candidat')),
            ],
            options={
                'verbose_name': 'lead qualifié',
                'verbose_name_plural': 'leads qualifiés',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureCRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('EN_REVUE', 'En revue'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('EN_ATTENTE', 'En attente (liste complémentaire)'), ('INSCRIT', 'Inscrit administrativement'), ('DESISTE', 'Désisté')], default='RECUE', max_length=15, verbose_name='statut')),
                ('note_interne', models.TextField(blank=True, help_text="Évaluation interne de l'établissement (non visible par le candidat)", verbose_name='note interne')),
                ('score_evaluation', models.FloatField(blank=True, help_text="Score attribué par l'établissement au dossier", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="score d'évaluation")),
                ('commentaire_etablissement', models.TextField(blank=True)),
                ('motif_refus', models.TextField(blank=True, verbose_name='motif de refus')),
                ('external_application_id', models.CharField(blank=True, help_text="ID dans le système de gestion interne de l'établissement", max_length=100, verbose_name='ID application externe')),
                ('is_synced_external', models.BooleanField(default=False, verbose_name="synchronisé à l'externe")),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_crm', to=settings.AUTH_USER_MODEL, verbose_name='candidat')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_crm', to='catalog.etablissement', verbose_name='établissement')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_crm', to='catalog.formation', verbose_name='formation visée')),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_generees', to='marketing.leadqualifie', verbose_name='lead source')),
            ],
            options={
                'verbose_name': 'candidature CRM',
                'verbose_name_plural': 'candidatures CRM',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='LogInteractionCRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('APPEL', 'Appel téléphonique'), ('SMS', 'SMS'), ('MESSAGE_INTERNE', 'Message interne'), ('VISIO', 'Visioconférence'), ('PRESENTIEL', 'Rencontre présentiel'), ('NOTE_INTERNE', 'Note interne')], max_length=20, verbose_name="type d'interaction")),
                ('sujet', models.CharField(blank=True, max_length=255, verbose_name='sujet')),
                ('contenu', models.TextField()),
                ('date_interaction', models.DateTimeField(auto_now_add=True)),
                ('is_automatique', models.BooleanField(default=False, help_text="True si l'interaction a été générée automatiquement", verbose_name='automatique')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_crm_initiees', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='marketing.candidaturecrm', verbose_name='candidature')),
            ],
            options={
                'verbose_name': "log d'interaction CRM",
                'verbose_name_plural': "logs d'interactions CRM",
                'ordering': ['-date_interaction'],
            },
        ),
        migrations.AddIndex(
            model_name='leadqualifie',
            index=models.Index(fields=['campagne', 'statut'], name='marketing_l_campagn_d41c13_idx'),
        ),
        migrations.AddIndex(
            model_name='leadqualifie',
            index=models.Index(fields=['candidat', '-date_generation'], name='marketing_l_candida_a53bc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadqualifie',
            unique_together={('campagne', 'candidat')},
        ),
        migrations.AddIndex(
            model_name='candidaturecrm',
            index=models.Index(fields=['etablissement', 'statut'], name='marketing_c_etablis_7f037f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidaturecrm',
            index=models.Index(fields=['candidat', '-date_reception'], name='marketing_c_candida_e6e757_idx'),
        ),
        migrations.AddIndex(
            model_name='campagnemarketing',
            index=models.Index(fields=['etablissement', 'statut'], name='marketing_c_etablis_f2cbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='campagnemarketing',
            index=models.Index(fields=['date_debut', 'date_fin'], name='marketing_c_date_de_847988_idx'),
        ),
    ]
