# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(help_text='Année de référence du classement', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='année')),
                ('rang_national', models.PositiveIntegerField(blank=True, help_text='Position dans le classement national', null=True, verbose_name='rang national')),
                ('rang_regional', models.PositiveIntegerField(blank=True, help_text="Position dans le classement régional (ex: Afrique de l'Ouest)", null=True, verbose_name='rang régional')),
                ('score_final', models.FloatField(default=0, help_text='Score composite sur 100', validators=[django.core.validators.MinValueValidator(0)], verbose_name='score final')),
                ('details_scores', models.JSONField(blank=True, default=dict, help_text="Ex: {'qualite_enseignement': 85, 'insertion_professionnelle': 78, 'recherche': 60, 'reputation': 72}", verbose_name='détails des scores')),
                ('methodology', models.TextField(blank=True, help_text='Description de la méthode de calcul et des critères utilisés', verbose_name='méthodologie')),
                ('is_published', models.BooleanField(default=False, help_text='Rendre ce classement visible publiquement', verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='catalog.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'classement',
                'verbose_name_plural': 'classements',
                'ordering': ['annee', 'rang_national'],
                'indexes': [models.Index(fields=['annee', 'rang_national'], name='ranking_cla_annee_e9d149_idx'), models.Index(fields=['is_published'], name='ranking_cla_is_publ_2cbdbc_idx')],
                'constraints': [models.UniqueConstraint(fields=('etablissement', 'annee'), name='unique_classement_etablissement_annee')],
            },
        ),
    ]
