# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(verbose_name='texte de la question')),
                ('texte_court', models.CharField(blank=True, max_length=100, verbose_name='texte court (pour mobile)')),
                ('explication', models.TextField(blank=True, help_text="Affichée si l'utilisateur demande de l'aide", verbose_name='explication / aide')),
                ('image', models.ImageField(blank=True, null=True, upload_to='orientation/questions/%Y/', verbose_name='image illustrative')),
                ('type', models.CharField(choices=[('CHOIX_UNIQUE', 'Choix unique (radio)'), ('CHOIX_MULTIPLE', 'Choix multiple (checkbox)'), ('ECHELLE_LIKERT', 'Échelle de Likert (1-5)'), ('CLASSEMENT', 'Classement / ordre de préférence'), ('OUVERTE', 'Question ouverte (texte)'), ('SITUATIONNELLE', 'Mise en situation')], default='ECHELLE_LIKERT', max_length=20, verbose_name='type de question')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre dans le test')),
                ('poids', models.FloatField(default=1.0, help_text='Multiplicateur pour le scoring', validators=[django.core.validators.MinValueValidator(0)], verbose_name='poids de la question')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('dimensions', models.JSONField(default=dict, help_text="Mapping dimension → coefficient. Ex: {'R': 1.0, 'I': 0.5} signifie que cette question évalue la dimension Réaliste (coef 1) et Investigateur (coef 0.5)", verbose_name='dimensions évaluées')),
                ('echelle_min', models.PositiveIntegerField(default=1, verbose_name='valeur min échelle')),
                ('echelle_max', models.PositiveIntegerField(default=5, verbose_name='valeur max échelle')),
                ('label_min', models.CharField(default="Pas du tout d'accord", max_length=50, verbose_name='label min')),
                ('label_max', models.CharField(default="Tout à fait d'accord", max_length=50, verbose_name='label max')),
                ('contexte', models.TextField(blank=True, verbose_name='contexte de la situation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['test', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(verbose_name='texte du choix')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('scores', models.JSONField(default=dict, help_text="Ex: {'R': 3, 'I': 1, 'S': 0} — Points ajoutés à chaque dimension si ce choix est sélectionné", verbose_name='scores par dimension')),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orientation.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'choix de réponse',
                'verbose_name_plural': 'choix de réponse',
                'ordering': ['question', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EXPIRE', 'Expiré (non terminé à temps)'), ('ABANDONNE', "Abandonné par l'utilisateur")], default='EN_COURS', max_length=20, verbose_name='statut')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='date de fin')),
                ('duree_reelle_secondes', models.PositiveIntegerField(default=0, verbose_name='durée réelle (secondes)')),
                ('nombre_questions_repondues', models.PositiveIntegerField(default=0)),
                ('nombre_questions_total', models.PositiveIntegerField(default=0)),
                ('progression', models.FloatField(default=0, verbose_name='progression (%)')),
                ('score_global', models.FloatField(default=0, verbose_name='score global')),
                ('profil_dominant', models.CharField(blank=True, help_text="Code RIASEC dominant, ex: 'R', 'I', etc.", max_length=5, verbose_name='profil dominant')),
                ('profil_secondaire', models.CharField(blank=True, max_length=5, verbose_name='profil secondaire')),
                ('code_holland', models.CharField(blank=True, help_text="Ex: 'RIA', 'SEC'", max_length=3, verbose_name='code Holland (3 lettres)')),
                ('scores_par_dimension', models.JSONField(default=dict, help_text="Ex: {'R': 75, 'I': 82, 'A': 45, 'S': 68, 'E': 55, 'C': 60}", verbose_name='scores par dimension')),
                ('appareil', models.CharField(blank=True, help_text='mobile, desktop, tablette', max_length=50, verbose_name='appareil utilisé')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reponses_tests', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'réponse utilisateur',
                'verbose_name_plural': 'réponses utilisateurs',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ResultatTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_global', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score global (0-100)')),
                ('scores_par_dimension', models.JSONField(default=dict, help_text="Ex: {'R': 75, 'I': 82, 'A': 45, 'S': 68, 'E': 55, 'C': 60}", verbose_name='scores par dimension (0-100 chacun)')),
                ('code_holland', models.CharField(blank=True, help_text="Ex: 'IRE' pour Investigateur-Réaliste-Entreprenant", max_length=3, verbose_name='code Holland (3 lettres)')),
                ('profil_dominant', models.CharField(blank=True, max_length=5, verbose_name='dimension dominante')),
                ('profil_secondaire', models.CharField(blank=True, max_length=5, verbose_name='dimension secondaire')),
                ('interpretation', models.TextField(blank=True, help_text="Texte explicatif généré pour l'étudiant", verbose_name='interprétation du résultat')),
                ('forces', models.JSONField(blank=True, default=list, verbose_name='forces identifiées')),
                ('axes_amelioration', models.JSONField(blank=True, default=list, verbose_name="axes d'amélioration")),
                ('evolution_vs_precedent', models.JSONField(blank=True, default=dict, help_text="Ex: {'R': +5, 'I': -2, 'A': +10} — Différence avec le test précédent du même type", verbose_name='évolution vs test précédent')),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('reponse_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='orientation.reponseutilisateur', verbose_name='réponse utilisateur')),
            ],
            options={
                'verbose_name': 'résultat de test',
                'verbose_name_plural': 'résultats de tests',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='TestOrientation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='nom du test')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_courte', models.CharField(blank=True, max_length=300, verbose_name='description courte')),
                ('type', models.CharField(choices=[('INTERETS', "Test d'intérêts (RIASEC)"), ('PERSONNALITE', 'Test de personnalité'), ('COMPETENCES', 'Test de compétences'), ('VALEURS', 'Test de valeurs professionnelles'), ('MIXTE', 'Test mixte (combiné)'), ('DIAGNOSTIC', 'Diagnostic rapide')], default='MIXTE', max_length=20, verbose_name='type de test')),
                ('duree_estimee_minutes', models.PositiveIntegerField(default=15, help_text='Durée moyenne pour compléter le test', verbose_name='durée estimée (minutes)')),
                ('nombre_questions', models.PositiveIntegerField(default=0, help_text='Calculé automatiquement', verbose_name='nombre de questions')),
                ('dimensions_evaluees', models.JSONField(default=list, help_text="Codes des dimensions : ['R', 'I', 'A', 'S', 'E', 'C']", verbose_name='dimensions évaluées')),
                ('methode_scoring', models.CharField(default='RIASEC_PONDERE', help_text='Algorithme utilisé pour le calcul des scores', max_length=50, verbose_name='méthode de scoring')),
                ('niveau_minimum', models.CharField(blank=True, help_text="Ex: 'Terminale', 'L1', etc.", max_length=20, verbose_name='niveau minimum requis')),
                ('age_minimum', models.PositiveIntegerField(default=15, verbose_name='âge minimum')),
                ('nombre_passations', models.PositiveIntegerField(default=0)),
                ('taux_completion', models.FloatField(default=0, verbose_name='taux de complétion (%)')),
                ('score_moyen', models.FloatField(default=0, verbose_name='score moyen global')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_public', models.BooleanField(default=True, help_text='Accessible à tous les utilisateurs', verbose_name='public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='date de publication')),
                ('source_scientifique', models.CharField(blank=True, help_text="Ex: 'Holland RIASEC', 'Big Five', etc.", max_length=255, verbose_name='source / référence scientifique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_crees', to=settings.AUTH_USER_MODEL, verbose_name='auteur du test')),
            ],
            options={
                'verbose_name': "test d'orientation",
                'verbose_name_plural': "tests d'orientation",
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='orientation.testorientation', verbose_name='test passé'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='orientation.testorientation', verbose_name='test associé'),
        ),
        migrations.CreateModel(
            name='DetailReponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choices_selectionnes', models.JSONField(blank=True, default=list, help_text='Liste des IDs des choix pour les questions à choix multiple', verbose_name='choix multiples sélectionnés')),
                ('valeur_echelle', models.PositiveIntegerField(blank=True, help_text='Valeur de 1 à 5 pour les questions Likert', null=True, verbose_name='valeur échelle (Likert)')),
                ('classement', models.JSONField(blank=True, default=list, help_text='Ordre des choix pour les questions de classement', verbose_name='classement')),
                ('reponse_ouverte', models.TextField(blank=True, verbose_name='réponse ouverte')),
                ('temps_reponse_secondes', models.PositiveIntegerField(default=0, verbose_name='temps de réponse (secondes)')),
                ('score_calcule', models.JSONField(blank=True, default=dict, help_text="Ex: {'R': 3, 'I': 1} — Points attribués pour cette réponse", verbose_name='score calculé par dimension')),
                ('choice_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='orientation.choice', verbose_name='choix sélectionné')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_reponses', to='orientation.question', verbose_name='question')),
                ('reponse_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orientation.reponseutilisateur', verbose_name='session de test')),
            ],
            options={
                'verbose_name': 'détail de réponse',
                'verbose_name_plural': 'détails de réponse',
                'ordering': ['reponse_utilisateur', 'question__ordre'],
                'constraints': [models.UniqueConstraint(fields=('reponse_utilisateur', 'question'), name='unique_reponse_par_question')],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_entite', models.CharField(choices=[('FORMATION', 'Formation'), ('METIER', 'Métier'), ('ETABLISSEMENT', 'Établissement')], max_length=20, verbose_name="type d'entité")),
                ('taux_compatibilite', models.FloatField(help_text="Pourcentage de compatibilité entre le profil et l'entité", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='taux de compatibilité (%)')),
                ('niveau_confiance', models.CharField(choices=[('TRES_HAUTE', 'Très haute (>85%)'), ('HAUTE', 'Haute (70-85%)'), ('MOYENNE', 'Moyenne (50-70%)'), ('FAIBLE', 'Faible (<50%)')], default='MOYENNE', max_length=20, verbose_name='niveau de confiance')),
                ('plan', models.CharField(choices=[('PRINCIPAL', 'Plan principal — Forte compatibilité'), ('ALTERNATIF', 'Plan alternatif — Bonne compatibilité'), ('EXPLORATOIRE', 'Plan exploratoire — À découvrir'), ('PASSERELLE', 'Plan passerelle — Reconversion')], default='ALTERNATIF', max_length=20, verbose_name='plan de recommandation')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre de priorité')),
                ('justification', models.TextField(blank=True, help_text='Pourquoi cette recommandation est pertinente pour ce profil', verbose_name='justification')),
                ('points_forts_match', models.JSONField(blank=True, default=list, help_text="Ex: ['Forte affinité analytique', 'Bon taux d\\'insertion']", verbose_name='points forts du match')),
                ('points_attention', models.JSONField(blank=True, default=list, help_text="Ex: ['Coût élevé', 'Concours d\\'entrée sélectif']", verbose_name="points d'attention")),
                ('a_ete_vue', models.BooleanField(default=False, verbose_name="vue par l'étudiant")),
                ('a_ete_favorisee', models.BooleanField(default=False, verbose_name='ajoutée aux favoris')),
                ('a_ete_cliquee', models.BooleanField(default=False, verbose_name='lien cliqué')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='catalog.etablissement', verbose_name='établissement recommandé')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='catalog.formation', verbose_name='formation recommandée')),
                ('metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='catalog.metier', verbose_name='métier recommandé')),
                ('resultat_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='orientation.resultattest', verbose_name='résultat de test')),
            ],
            options={
                'verbose_name': 'recommandation',
                'verbose_name_plural': 'recommandations',
                'ordering': ['resultat_test', 'plan', 'ordre', '-taux_compatibilite'],
                'indexes': [models.Index(fields=['etudiant', '-created_at'], name='orientation_etudian_b7c1bf_idx'), models.Index(fields=['type_entite'], name='orientation_type_en_fd95d0_idx'), models.Index(fields=['plan'], name='orientation_plan_043f86_idx'), models.Index(fields=['-taux_compatibilite'], name='orientation_taux_co_fd3609_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reponseutilisateur',
            index=models.Index(fields=['etudiant', 'test'], name='orientation_etudian_b4cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='reponseutilisateur',
            index=models.Index(fields=['statut'], name='orientation_statut_83f1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='reponseutilisateur',
            index=models.Index(fields=['-date_debut'], name='orientation_date_de_15e454_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'ordre'], name='orientation_test_id_3c083c_idx'),
        ),
    ]
