# Generated by Django 6.0.6 on 2026-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponseutilisateur',
            name='code_holland',
            field=models.CharField(blank=True, help_text="Ex: 'RIA', 'SEC' ou 'N-ENV-I'", max_length=15, verbose_name='code profil (Holland ou multi-domaine)'),
        ),
        migrations.AlterField(
            model_name='resultattest',
            name='code_holland',
            field=models.CharField(blank=True, help_text="Ex: 'IRE' (RIASEC) ou 'N-ENV-I' (multi-domaine)", max_length=15, verbose_name='code profil (Holland ou multi-domaine)'),
        ),
    ]
