# Generated by Django 5.1.3 on 2026-07-02 04:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0002_extend_code_holland_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAccompagnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('REFUSEE', 'Refusée'), ('ANNULEE', "Annulée par l'étudiant")], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('motif', models.TextField(help_text="Expliquez pourquoi vous avez besoin d'accompagnement", verbose_name='motif de la demande')),
                ('domaines_concernes', models.JSONField(blank=True, default=list, help_text="Ex: ['Informatique', 'Gestion']", verbose_name='domaines concernés')),
                ('message_reponse', models.TextField(blank=True, help_text="Réponse du conseiller lors de l'acceptation ou du refus", verbose_name='message de réponse')),
                ('note_conseiller', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note du conseiller (0-5)')),
                ('commentaire_note', models.TextField(blank=True, verbose_name='commentaire sur la note')),
                ('ristourne_generee', models.BooleanField(default=False, verbose_name='ristourne générée')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='date de la demande')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='date de réponse')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='date de clôture')),
                ('conseiller', models.ForeignKey(blank=True, limit_choices_to={'role': 'COUNSELOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompagnements_recus', to=settings.AUTH_USER_MODEL, verbose_name='conseiller')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_accompagnement', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('resultat_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_accompagnement', to='orientation.resultattest', verbose_name='résultat de test associé')),
            ],
            options={
                'verbose_name': "demande d'accompagnement",
                'verbose_name_plural': "demandes d'accompagnement",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='MessageAccompagnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('est_lu', models.BooleanField(default=False, verbose_name='lu par le destinataire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_accompagnement', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orientation.demandeaccompagnement', verbose_name='demande')),
            ],
            options={
                'verbose_name': "message d'accompagnement",
                'verbose_name_plural': "messages d'accompagnement",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionProposee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField(verbose_name='texte de la question')),
                ('explication', models.TextField(blank=True, help_text="Aide pour l'étudiant ou contexte de la question", verbose_name='explication / contexte')),
                ('type', models.CharField(choices=[('ECHELLE_LIKERT', 'Échelle de Likert (1-5)'), ('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple'), ('SITUATIONNELLE', 'Mise en situation')], default='ECHELLE_LIKERT', max_length=20, verbose_name='type de question')),
                ('dimensions', models.JSONField(default=dict, help_text="Ex: {'R': 0.8, 'I': 0.5} — dimension RIASEC et son coefficient", verbose_name='dimensions évaluées')),
                ('poids', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='poids de la question')),
                ('contexte_situation', models.TextField(blank=True, help_text='Pour les questions situationnelles uniquement', verbose_name='contexte de la situation')),
                ('justification_proposition', models.TextField(blank=True, help_text='Pourquoi cette question est pertinente pour les étudiants', verbose_name='justification de la proposition')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'approbation"), ('APPROUVEE', 'Approuvée et intégrée'), ('REJETEE', 'Rejetée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='motif du rejet')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('conseiller', models.ForeignKey(limit_choices_to={'role': 'COUNSELOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions_proposees', to=settings.AUTH_USER_MODEL, verbose_name='conseiller proposant')),
                ('question_creee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depuis_proposition', to='orientation.question', verbose_name='question créée')),
                ('test_cible', models.ForeignKey(blank=True, help_text='Test dans lequel intégrer la question (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_proposees', to='orientation.testorientation', verbose_name='test cible')),
                ('traite_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_traitees', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': 'question proposée',
                'verbose_name_plural': 'questions proposées',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.AddIndex(
            model_name='demandeaccompagnement',
            index=models.Index(fields=['etudiant', 'statut'], name='orientation_etudian_8ae230_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeaccompagnement',
            index=models.Index(fields=['conseiller', 'statut'], name='orientation_conseil_738b30_idx'),
        ),
        migrations.AddIndex(
            model_name='questionproposee',
            index=models.Index(fields=['statut'], name='orientation_statut_142122_idx'),
        ),
        migrations.AddIndex(
            model_name='questionproposee',
            index=models.Index(fields=['conseiller', 'statut'], name='orientation_conseil_f328c8_idx'),
        ),
    ]
