# Generated by Django 5.1.3 on 2026-07-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0004_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorientation',
            name='type',
            field=models.CharField(choices=[('INTERETS', "Test d'intérêts (RIASEC)"), ('PERSONNALITE', 'Test de personnalité'), ('COMPETENCES', 'Test de compétences'), ('VALEURS', 'Test de valeurs professionnelles'), ('IKIGAI', 'Test Ikigai (4 piliers)'), ('MIXTE', 'Test mixte (combiné RIASEC + Ikigai)'), ('DIAGNOSTIC', 'Diagnostic rapide')], default='MIXTE', max_length=20, verbose_name='type de test'),
        ),
    ]
