# Generated by Django 5.1.3 on 2026-07-12 05:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0005_ikigai_piliers_enum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCollective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.CharField(choices=[('ATELIER_ORIENTATION', "Atelier d'orientation"), ('INFO_COLLECTIVE', 'Info collective école/filière'), ('WEBINAIRE_METIER', 'Webinaire métier'), ('SOUTIEN_PARENTS', 'Session soutien parents'), ('PREP_CONCOURS', 'Préparation concours'), ('COACHING_GROUPE', 'Coaching de groupe')], default='ATELIER_ORIENTATION', max_length=30, verbose_name='type de session')),
                ('format', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('VISIO', 'Visioconférence'), ('HYBRIDE', 'Hybride (présentiel + visio)')], default='VISIO', max_length=15, verbose_name='format')),
                ('lieu', models.CharField(blank=True, help_text='Adresse physique si présentiel/hybride', max_length=255, verbose_name='lieu (présentiel)')),
                ('lien_visio', models.URLField(blank=True, help_text='Lien Google Meet, Zoom, Jitsi, etc.', verbose_name='lien visio')),
                ('date_debut', models.DateTimeField(db_index=True, verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='récurrente')),
                ('frequence_recurrence', models.CharField(blank=True, help_text="Ex: 'HEBDOMADAIRE', 'MENSUELLE'", max_length=20, verbose_name='fréquence récurrence')),
                ('capacite_max', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='capacité maximale')),
                ('inscription_obligatoire', models.BooleanField(default=True, verbose_name='inscription obligatoire')),
                ('public_cible', models.CharField(default='Tous', help_text="Ex: 'Terminales D', 'Parents de 3e', 'Étudiants L1'", max_length=255, verbose_name='public cible')),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée'), ('REPORTABLE', 'À reporter')], default='PROGRAMMEE', max_length=15, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_animees', to=settings.AUTH_USER_MODEL, verbose_name='conseiller animateur')),
            ],
            options={
                'verbose_name': 'session collective',
                'verbose_name_plural': 'sessions collectives',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False, help_text='Marqué présent après la session', verbose_name='présent')),
                ('note_retour', models.TextField(blank=True, help_text='Retour du participant après la session', verbose_name='note de retour')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_inscrites', to=settings.AUTH_USER_MODEL, verbose_name='participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='orientation.sessioncollective', verbose_name='session')),
            ],
            options={
                'verbose_name': 'inscription à session',
                'verbose_name_plural': 'inscriptions à sessions',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AddIndex(
            model_name='sessioncollective',
            index=models.Index(fields=['conseiller', 'statut'], name='orientation_conseil_89572d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncollective',
            index=models.Index(fields=['date_debut'], name='orientation_date_de_195e26_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncollective',
            index=models.Index(fields=['type', 'statut'], name='orientation_type_9d19e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionsession',
            unique_together={('session', 'participant')},
        ),
    ]
