# Generated by Django 5.1.3 on 2026-07-12 05:35

import apps.compliance.encryption_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0006_sessions_collectives_avis_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultattest',
            name='interpretation',
            field=apps.compliance.encryption_fields.EncryptedTextField(blank=True, help_text="Texte explicatif généré pour l'étudiant (chiffré au repos)", verbose_name='interprétation du résultat'),
        ),
        migrations.AlterField(
            model_name='resultattest',
            name='scores_par_dimension',
            field=apps.compliance.encryption_fields.EncryptedJSONField(default=dict, help_text="Ex: {'R': 75, 'I': 82, 'A': 45, 'S': 68, 'E': 55, 'C': 60}", verbose_name='scores par dimension (0-100 chacun)'),
        ),
    ]
