# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='date')),
                ('nouveaux_utilisateurs', models.PositiveIntegerField(default=0)),
                ('utilisateurs_actifs', models.PositiveIntegerField(default=0)),
                ('pages_vues', models.PositiveIntegerField(default=0)),
                ('sessions_uniques', models.PositiveIntegerField(default=0)),
                ('tests_demarres', models.PositiveIntegerField(default=0)),
                ('tests_completes', models.PositiveIntegerField(default=0)),
                ('recommandations_generees', models.PositiveIntegerField(default=0)),
                ('formations_consultees', models.PositiveIntegerField(default=0)),
                ('voeux_crees', models.PositiveIntegerField(default=0)),
                ('paiements_reussis', models.PositiveIntegerField(default=0)),
                ('revenus_fcfa', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='revenus (FCFA)')),
                ('top_formations', models.JSONField(blank=True, default=list)),
                ('top_recherches', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'statistique quotidienne',
                'verbose_name_plural': 'statistiques quotidiennes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code unique')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('formule', models.TextField(blank=True, verbose_name='formule de calcul')),
                ('categorie', models.CharField(choices=[('ACQUISITION', 'Acquisition'), ('ENGAGEMENT', 'Engagement'), ('ORIENTATION', 'Orientation'), ('CONVERSION', 'Conversion'), ('RETENTION', 'Rétention'), ('IMPACT', 'Impact social'), ('TECHNIQUE', 'Technique')], max_length=20, verbose_name='catégorie')),
                ('periode', models.CharField(default='MENSUELLE', max_length=20, verbose_name='période')),
                ('unite', models.CharField(default='nombre', max_length=50, verbose_name='unité')),
                ('icone', models.CharField(default='📊', max_length=10, verbose_name='icône')),
                ('couleur', models.CharField(default='#3B82F6', max_length=7, verbose_name='couleur (hex)')),
                ('cible', models.FloatField(blank=True, null=True, verbose_name='valeur cible')),
                ('seuil_alerte_bas', models.FloatField(blank=True, null=True, verbose_name='seuil alerte bas')),
                ('seuil_alerte_haut', models.FloatField(blank=True, null=True, verbose_name='seuil alerte haut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('roles_access', models.JSONField(blank=True, default=list, verbose_name='rôles ayant accès')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'définition KPI',
                'verbose_name_plural': 'définitions KPI',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sections', models.JSONField(default=list, verbose_name='sections du rapport')),
                ('filtres_defaut', models.JSONField(blank=True, default=dict, verbose_name='filtres par défaut')),
                ('formats_disponibles', models.JSONField(default=list, verbose_name="formats d'export")),
                ('roles_access', models.JSONField(blank=True, default=list, verbose_name='rôles ayant accès')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'template de rapport',
                'verbose_name_plural': 'templates de rapport',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('filtres_appliques', models.JSONField(blank=True, default=dict, verbose_name='filtres appliqués')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='données du rapport')),
                ('format_export', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('JSON', 'JSON')], max_length=10, verbose_name="format d'export")),
                ('fichier', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='fichier')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de génération'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec')], default='EN_COURS', max_length=20, verbose_name='statut')),
                ('message_erreur', models.TextField(blank=True)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('dernier_telechargement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_genres', to=settings.AUTH_USER_MODEL, verbose_name='généré par')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='analytics.reporttemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_action', models.CharField(choices=[('PAGE_VIEW', 'Vue de page'), ('SEARCH', 'Recherche'), ('FORMATION_VIEW', 'Formation consultée'), ('FAVORI_ADDED', 'Favori ajouté'), ('VOEU_CREATED', 'Vœu créé'), ('TEST_STARTED', 'Test démarré'), ('TEST_COMPLETED', 'Test terminé'), ('PAYMENT_INITIATED', 'Paiement initié'), ('PAYMENT_COMPLETED', 'Paiement réussi'), ('EVENT_REGISTERED', 'Inscription événement')], db_index=True, max_length=30, verbose_name="type d'action")),
                ('entite_type', models.CharField(blank=True, max_length=50, verbose_name="type d'entité")),
                ('entite_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'entité")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "log d'action",
                'verbose_name_plural': "logs d'actions",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type_action', '-created_at'], name='analytics_a_type_ac_d989dd_idx'), models.Index(fields=['utilisateur', '-created_at'], name='analytics_a_utilisa_acd7d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormationView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='durée de consultation (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.formation', verbose_name='formation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_views', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vue de formation',
                'verbose_name_plural': 'vues de formations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['formation', '-created_at'], name='analytics_f_formati_a15683_idx'), models.Index(fields=['utilisateur', '-created_at'], name='analytics_f_utilisa_c15b9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('periode', models.CharField(default='MENSUELLE', max_length=20, verbose_name='période')),
                ('valeur', models.FloatField(verbose_name='valeur')),
                ('valeur_precedente', models.FloatField(blank=True, null=True, verbose_name='valeur précédente')),
                ('variation', models.FloatField(blank=True, null=True, verbose_name='variation (%)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.kpidefinition', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'snapshot KPI',
                'verbose_name_plural': 'snapshots KPI',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['kpi', '-date'], name='analytics_k_kpi_id_45aef1_idx')],
                'constraints': [models.UniqueConstraint(fields=('kpi', 'date', 'periode'), name='unique_kpi_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='chemin')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vue de page',
                'verbose_name_plural': 'vues de page',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', '-created_at'], name='analytics_p_path_33d66e_idx'), models.Index(fields=['utilisateur', '-created_at'], name='analytics_p_utilisa_6c6512_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=500, verbose_name='requête')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='nombre de résultats')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'requête de recherche',
                'verbose_name_plural': 'requêtes de recherche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', '-created_at'], name='analytics_s_query_e6d058_idx'), models.Index(fields=['utilisateur', '-created_at'], name='analytics_s_utilisa_2f3ffa_idx')],
            },
        ),
    ]
