# Generated by Django 5.1.3 on 2026-07-10 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='ateliers_virtuels_disponibles',
            field=models.BooleanField(default=False, help_text="Indique si l'établissement propose des ateliers virtuels interactifs", verbose_name='ateliers virtuels disponibles'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='galerie_3d',
            field=models.JSONField(blank=True, default=list, help_text="Liste de scènes 3D. Format: [{'titre': 'Campus principal', 'type': 'matterport'|'sketchfab'|'360', 'url': 'https://...', 'vignette': 'https://...'}]", verbose_name='galerie 3D / immersive'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='video_presentation_url',
            field=models.URLField(blank=True, help_text="Lien YouTube/Vimeo d'une vidéo immersive de présentation", verbose_name='URL vidéo de présentation'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='visite_virtuelle_url',
            field=models.URLField(blank=True, help_text='Lien vers une visite 360° ou un modèle 3D (Matterport, Sketchfab, etc.)', verbose_name='URL de visite virtuelle 3D'),
        ),
        migrations.CreateModel(
            name='ResultatSimulateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyenne_saisie', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="moyenne saisie par l'étudiant")),
                ('serie_bac_saisie', models.CharField(blank=True, max_length=10, verbose_name='série de bac saisie')),
                ('pourcentage_chances', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="pourcentage de chances d'admission")),
                ('niveau_confiance', models.CharField(default='MOYEN', help_text='Faible, Moyen, Élevé — selon la quantité de données historiques', max_length=20, verbose_name='niveau de confiance')),
                ('explication', models.JSONField(default=dict, help_text='Décomposition du calcul pour transparence', verbose_name='explication détaillée')),
                ('recommandations', models.JSONField(default=list, help_text='Liste de recommandations pour améliorer ses chances', verbose_name='recommandations')),
                ('date_simulation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations_admission', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='catalog.formation', verbose_name='formation')),
            ],
            options={
                'verbose_name': 'résultat de simulation',
                'verbose_name_plural': 'résultats de simulations',
                'ordering': ['-date_simulation'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(help_text='Année du concours / admission', verbose_name='année')),
                ('moyenne_bac', models.FloatField(help_text='Moyenne /20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='moyenne au bac')),
                ('serie_bac', models.CharField(help_text='Ex: C, D, G2, L, etc.', max_length=10, verbose_name='série de bac')),
                ('mention', models.CharField(blank=True, help_text='Passable, Assez Bien, Bien, Très Bien', max_length=20, verbose_name='mention')),
                ('a_ete_admis', models.BooleanField(help_text='True si le candidat a été admis cette année-là', verbose_name='a été admis')),
                ('rang_admission', models.PositiveIntegerField(blank=True, help_text='Rang dans le classement (si admis)', null=True, verbose_name="rang d'admission")),
                ('nombre_candidats_annee', models.PositiveIntegerField(default=0, verbose_name='nombre total de candidats cette année')),
                ('nombre_admis_annee', models.PositiveIntegerField(default=0, verbose_name="nombre total d'admis cette année")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_admissions', to='catalog.formation', verbose_name='formation')),
            ],
            options={
                'verbose_name': "historique d'admission",
                'verbose_name_plural': "historiques d'admissions",
                'ordering': ['-annee', '-created_at'],
                'indexes': [models.Index(fields=['formation', 'annee'], name='catalog_adm_formati_fe1804_idx'), models.Index(fields=['a_ete_admis'], name='catalog_adm_a_ete_a_705872_idx')],
            },
        ),
    ]
