# Generated by Django 5.1.3 on 2026-07-12 05:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_simulateur_admission_visites_3d'),
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisAlumni',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_entree', models.PositiveIntegerField(help_text="Année d'inscription dans l'établissement", verbose_name="année d'entrée")),
                ('annee_sortie', models.PositiveIntegerField(help_text="Année d'obtention du diplôme ou de départ", verbose_name='année de sortie')),
                ('formation_suivie', models.CharField(blank=True, help_text='Nom de la formation/diplôme', max_length=255, verbose_name='formation suivie')),
                ('diplome_obtenu', models.BooleanField(default=True, verbose_name='diplôme obtenu')),
                ('note_globale', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note globale')),
                ('note_enseignement', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name="qualité de l'enseignement")),
                ('note_infrastructures', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='infrastructures')),
                ('note_vie_etudiante', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='vie étudiante')),
                ('note_insertion_pro', models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='insertion professionnelle')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('contenu', models.TextField(help_text="Témoignage détaillé de l'expérience dans l'établissement", verbose_name='contenu')),
                ('points_forts', models.TextField(blank=True, help_text='Ce que vous avez apprécié', verbose_name='points forts')),
                ('points_faibles', models.TextField(blank=True, help_text='Ce qui peut être amélioré', verbose_name='points faibles')),
                ('recommande', models.BooleanField(default=True, verbose_name='recommande cet établissement')),
                ('situation_actuelle', models.CharField(blank=True, help_text="Ex: 'En poste chez Google', 'En thèse à Paris', etc.", max_length=255, verbose_name='situation actuelle')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de vérification'), ('CERTIFIE', 'Certifié (alumni vérifié)'), ('REFUSE', 'Refusé (non vérifiable)'), ('SIGNALE', 'Signalé (modération)')], default='EN_ATTENTE', max_length=15, verbose_name='statut')),
                ('is_certified', models.BooleanField(default=False, help_text="True si l'auteur a été vérifié comme alumni de l'établissement", verbose_name='certifié')),
                ('date_certification', models.DateTimeField(blank=True, null=True)),
                ('justificatif', models.FileField(blank=True, help_text='Diplôme, certificat de scolarité, etc.', null=True, upload_to='avis_alumni/justificatifs/%Y/%m/', verbose_name='justificatif')),
                ('nombre_signalements', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_alumni_donnes', to=settings.AUTH_USER_MODEL, verbose_name='auteur (alumni)')),
                ('certifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_alumni_certifies', to=settings.AUTH_USER_MODEL, verbose_name='certifié par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_alumni', to='catalog.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'avis alumni',
                'verbose_name_plural': 'avis alumni',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['etablissement', 'is_certified'], name='community_a_etablis_3732b0_idx'), models.Index(fields=['statut'], name='community_a_statut_059fdf_idx')],
                'unique_together': {('etablissement', 'auteur')},
            },
        ),
    ]
