# Generated by Django 5.1.3 on 2026-07-12 05:35

import apps.compliance.encryption_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_sessions_collectives_avis_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprive',
            name='contenu',
            field=apps.compliance.encryption_fields.EncryptedTextField(verbose_name='contenu'),
        ),
    ]
