# Generated by Django 5.1.3 on 2026-06-28 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('type_notification', models.CharField(choices=[('INFO', 'ℹ️ Information'), ('SUCCESS', '✅ Succès'), ('WARNING', '⚠️ Avertissement'), ('ALERT', '🚨 Alerte'), ('REMINDER', '🔔 Rappel'), ('BIENVENUE', '👋 Bienvenue'), ('VERIF_EMAIL', '📧 Vérification email'), ('RESET_PASSWORD', '🔐 Réinitialisation mot de passe'), ('COMPTE_ACTIVE', '✅ Compte activé'), ('TEST_COMPLETE', "🎯 Test d'orientation terminé"), ('NOUVELLE_REC', '💡 Nouvelle recommandation'), ('VOEU_SOUMIS', '📤 Vœu soumis'), ('VOEU_ACCEPTE', '✅ Vœu accepté'), ('VOEU_REFUSE', '❌ Vœu refusé'), ('DEMARCHE_ECHEANCE', '⏰ Échéance démarche'), ('INSCR_EVT', '🎟️ Inscription événement'), ('RAPPEL_J7', '📅 Rappel J-7'), ('RAPPEL_J1', '📅 Rappel J-1'), ('RAPPEL_J0', '📅 Rappel jour J'), ('NOUV_MESSAGE', '💬 Nouveau message'), ('PERSONNALISEE', '📝 Notification personnalisée'), ('NEWSLETTER', '📰 Newsletter')], default='INFO', max_length=30, verbose_name='type')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('action_url', models.URLField(blank=True, help_text="Lien vers lequel rediriger l'utilisateur", verbose_name="URL d'action")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type_notification', '-created_at'], name='notificatio_type_no_325ec1_idx')],
            },
        ),
    ]
